### ISSUE TITLE
Small issue with Akeeba Backup

### ISSUE THREAD

**Issue by dautrich** [hotmango/Atum-Custom-UserCss#1]
When using Akeeba Backup together with your user.css, some dialogues in the Akeeba escape your CSS, you might take a look.

**Comment by RussW** [comment]
Thanks for the report Rolf, can you be a little more explicit or provide an image of what you are seeing, I can't see anything going awry, even with darkmode enabled.

To quite some degree Akeeba (and I believe Tassos extensions) use it's own extensive custom css styling beyond the Joomla standard styles so unless I cater specifically for these types of extensions, it is likely that some parts wont follow the custom user.css rules.  

Let me know what/where you are seeing issues and I'll have a look it though.

**Comment by RussW** [comment]
I've just updated the .card css so that "inner cards" (cards within cards, that are used in Akeeba) no longer acquire the box-shadow & hover. Is this what you were meaning?

**Comment by dautrich** [comment]
I didn't find much anymore. There is one small thing: Akeeba Backup shows buttons in different sizes / font sizes.

![Bildschirminhalt erfassen-2](https://github.com/hotmango/Atum-Custom-UserCss/assets/7933215/95d67b6a-de52-4f2d-a945-0c3bccedd410)

The two buttons to the left are too big IMHO. The right one is okay. I don't know why different CSS styles are applied here.

I don't think it's a real issue. But if you can easily find a patch, it would be nice.

**Comment by RussW** [comment]
@dautrich, I see your point, the mixed use of the bootstrap btn sizes within similar context is a little odd and visually strange, with little real purpose. Having said this, it is the extension developers choice of UI/UX at that point, making extensive global changes to specifically suit just this one extension is likely to cause more issues later (if/as other extensions are installed) or break UI consistency elsewhere.

Having said the above, I have looked at the generic sizing, spacing and padding of the default BS (with standard Atum modifications) .btn and have subsequently reduced the padding, line-height and font-size slightly globally to be more inline with the rest of the override style. Hope this goes some way toward your preference. Let me know.

**Comment by dautrich** [comment]
@RussW 
I like it! Well done.

**Comment by RussW** [comment]
Thanks for your time and considerations, appreciated as always @dautrich.
Unless there are any other anomalies you see I'll close this for now and make a release.
