### ISSUE TITLE
Issues with VirtueMart

### ISSUE THREAD

**Issue by keep** [hotmango/Atum-Custom-UserCss#2]
When using this with VirtueMart, it duplicates the dropdowns, displaying both the standard <select> and the 'chosen' modified version.

Additionally, VirtueMart employs toolbar buttons differently, and when the button text is lengthy, it extends beyond the box.

Tested with Joomla 4.4.2 and VM 4.2.4.

**Comment by RussW** [comment]
Thank you for taking the time to try the custom user.css for the Atum administrator template. It is only targeted at overriding the standard Joomla css.

I have not tested this css with VM as I am not a user, so if you could provide some images to better describe the problem(s) you are seeing that would be very helpful in potentially finding any CSS clashed there may be and I might be able to resolve them.

**Comment by keep** [comment]
Thanks.
This is the default layout: https://i.postimg.cc/q7BRs8rh/k-p.png
This is the modified one: https://i.postimg.cc/2852Ktx2/k-p.png

I think this issue is caused by using display: block !important; for every <select> in line 238. I'm not a CSS expert, but at first glance, it should be select:not(:hidden)?

**Comment by RussW** [comment]
have you tried opening in inspect view and disabling the display display:block!important; statement (or editing the user.css itself? From what I can see, the default Joomla! template.css sets display to block on that element, however it seems that VM is doing it's own thing with select elements, can you try the following please?

Can you remove the !important on the display statement mentioned and directly under the mentioned CSS block (above) add the following;

.custom-select, .form-select {
  -webkit-appearance: none;
  -moz-appearance: none;
  appearance: none;
}

thank you for your time,

**Comment by keep** [comment]
Yup, it solved the issues with the dropdowns in VM

**Comment by RussW** [comment]
awesome, thank you for taking the time, bringing this to my attention and testing, I'll put this in the next release.

**Comment by RussW** [comment]
Closed to new release v0.42.2
