### ISSUE TITLE
Font does not fit in pulldown dialogbox.

### ISSUE THREAD

**Issue by WimVanGrimbergen** [hotmango/Atum-Custom-UserCss#4]
On our website we are making use of AcyMailing.
In the configuration section of Acymailing one can make selections in pulldown boxes. The text in those boxes only fit half, or are cropped half. Whenever one has to enter himself text in a dialogbox the entry is correct. See attached screenshot.

![Acymailing-atumccs](https://github.com/hotmango/Atum-Custom-UserCss/assets/10197118/76ec3168-86c7-4a95-a07f-5fd16196e837)

**Comment by RussW** [comment]
From what I can determine, the height of these elements is set by the AcyMailing CSS and does not conform to the standard Joomla! styling for J4 or J5.  

in addition to this it is our understanding that AcyMailing v5 is no-longer supported by the AcyMailing team themselves, as such we have tested with the current latest version (being v9.2.0 at this time) and there are no such issues observed.

If, you would like to add the following CSS statement to __line 238 of the current user.css__ file this will overcome your issue until you update to their latest supported release.
 
select,
.js-stools-container-box .custom-select,
.form-select {
	display: block !important;
	width: 100% !important;
	padding: 0.5rem 3rem 0.5rem 1rem !important;
	__min-height: 34px !important;__
}
