### ISSUE TITLE
[0.42.3 - Pre5.1] Issue on Home Dashboard in Dark Mode 

### ISSUE THREAD

**Issue by dautrich** [hotmango/Atum-Custom-UserCss#5]
### Testing Instructions

1. Install fresh J4.4.4
2. Set system (and/or browser) to dark mode
3. Inspect Home Dashboard

### Expected Result
All items on dashboard are clearly visible.

### Current Result
1. In the card "Sample Data", text is not readable.
2. The modification symbol in the top right corner of each card is not visible.

![grafik](https://github.com/hotmango/Atum-Custom-UserCss/assets/7933215/c2b474ab-f2c5-4b49-b81a-5a4de1912a54)

**Comment by RussW** [comment]
Hi Rolf,

this should resolve the J4 commissions/changes
[Download ZIP](https://github.com/hotmango/Atum-Custom-UserCss/archive/refs/heads/main.zip)

**Comment by dautrich** [comment]
Problem solved

**Comment by dautrich** [comment]
Problem solved
