### ISSUE TITLE
[5.1] Issue with J5.1 Dark Mode Switch

### ISSUE THREAD

**Issue by dautrich** [hotmango/Atum-Custom-UserCss#7]
Two preliminary comments:
- Joomla 5.1 comes with a dark mode switch (which is perfectly hidden and must be activated by saving the Atum template style once; has been declared a bug and will be corrected in J5.1.1).
- My favorite browser for Joomla work is Firefox, equipped with extension “Toggle Dark Mode”.

There is a difference in handling the switching between dark and light modes between a standard J5.1.0 and one with your user.css:
- Without your user.css, the Joomla backend ignores the browser switch completely. The only way to exchange the mode is using Joomla's own switch.
- With your user.css, the backend behaves differently: 

When I'm in dark mode and use Joomla's Dark Mode switch:
![grafik](https://github.com/hotmango/Atum-Custom-UserCss/assets/7933215/17d2dc8a-e2a6-4db2-9284-c471ec264ee8)
... I end up with something in-between:
![grafik](https://github.com/hotmango/Atum-Custom-UserCss/assets/7933215/e06e978d-24fe-4d02-843b-68d6d8077fb1)
Only when I use the browser's Toggle Dark Mode:
![grafik](https://github.com/hotmango/Atum-Custom-UserCss/assets/7933215/27169f24-f829-46b1-8704-4fc952cfa2b0)
... I finally end up in a correct light mode:
![grafik](https://github.com/hotmango/Atum-Custom-UserCss/assets/7933215/f0a4289c-44c0-4477-923e-3add57a4f0e7)

When I use a different browser, i.e. Edge or a Firefox without the extension, I end up in the in-between state (second slide).

**Comment by RussW** [comment]
could I ask if you could complete the same test again with your browser switcher plugin and inspect the page for what, if any, css class and data-element is added to the "body" tag.
I think the native Joomla method is to add the "prefers-color-scheme: dark | light" to the body tag to instigate the change, there may be some confusion when using the browser plugin as joomla is not then adding the data tag to the body.

How does it react for you if you use the browser "inspect" rendering option to change the coloe-scheme mode?

Can you also let me know which plugin it is that you use please? Thank you.

**Comment by RussW** [comment]
does this detect the dark mode switch any better for you now @dautrich 
https://github.com/hotmango/Atum-Custom-UserCss/blob/main/J5.1_above-user.css

**Comment by dautrich** [comment]
> Can you also let me know which plugin it is that you use please?

The Firefox extension is called “Toggle Dark Mode”.

**Comment by dautrich** [comment]
With Firefox extension installed:

![grafik](https://github.com/hotmango/Atum-Custom-UserCss/assets/7933215/9be738fa-5727-4ee6-abf8-a7cc67baafde)

**Comment by dautrich** [comment]
With Firefox extension deactivated:

![grafik](https://github.com/hotmango/Atum-Custom-UserCss/assets/7933215/7ceb4563-4a02-4fd9-a3ff-28a97dbdd8b3)

**Comment by dautrich** [comment]
With today's version, the Joomla Dark Mode switch works correctly. 

After that first test, I re-activated the browser extension. The Joomla Dark Mode switch keeps on working, the browser's switch works as well (but for all tabs, of course).

**Comment by dautrich** [comment]
I close this issue as completed.

**Comment by RussW** [comment]
thank you so much for your time with this, really do appreciate your help and testing. I've a few things to clean up and fix up in the latest branch for both the J4 & J5.1 versions and I'll do another proper release.
